[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
custody = "Gcu1vbed9bwpfwU9PCnJw8QanQfVHfETWxAK3EZczbgo"
glam = "Gco1pcjxCMYjKJjSNJ7mKV7qezeUTE7arXJgy7PAPNRc"
policy = "Gpo1jXtEFepqyPQWTG7oDJrg8rye8JL3zcsczHzXKqLt"
pricing = "Gpr1WZZXAty2L9eiMwZPC7ra69vMFojhdqDuiRHkQQQp"
strategy = "Gst1YGe5vKURSWfCqM7GhZys1oML9E9t91WRyV2rt4yS"

[programs.localnet]
custody = "Gcu1vbed9bwpfwU9PCnJw8QanQfVHfETWxAK3EZczbgo"
glam = "Gco1pcjxCMYjKJjSNJ7mKV7qezeUTE7arXJgy7PAPNRc"
policy = "Gpo1jXtEFepqyPQWTG7oDJrg8rye8JL3zcsczHzXKqLt"
pricing = "Gpr1WZZXAty2L9eiMwZPC7ra69vMFojhdqDuiRHkQQQp"
strategy = "Gst1YGe5vKURSWfCqM7GhZys1oML9E9t91WRyV2rt4yS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
#cluster = "devnet"
wallet = "/Users/ec/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest --verbose --testNamePattern investor"
#test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000000
#shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
# Pyth SOL/USD
address = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"
[[test.validator.clone]]
# Pyth USDC/USD
address = "5SSkXsEKQepHHAewytPVwdej4epN1nxgLVM84L4KXgy7"
[[test.validator.clone]]
# Pyth BTC/USD
address = "HovQMDrbAgAYPCmHVSrezcSmkMtXSSUsLDFANExrZh2J"
[[test.validator.clone]]
# Pyth ETH/USD
address = "EdVCmQ9FSPcVe5YySXDPCRmc8aDQLKJ9xvYBMZPie1Vw"
[[test.validator.clone]]
# Drift program
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
