[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
anchor-gen = "0.3.0"

solana-program = "=1.17.22"
spl-associated-token-account = "=2.2.0"
spl-token = "=4.0.0"
spl-token-2022 = "=0.9.0"
num_enum = "=0.7.0"

spl-tlv-account-resolution = "0.5.2"
spl-transfer-hook-interface = "0.5.1"
pyth-sdk-solana = "0.10.0"

drift = { path="./deps/drift" }
